#! /bin/bash

gmapping_Name=slam_gmapping
gmappingNumber=`ps -ef |grep -w $gmapping_Name|grep -v grep|wc -l`
if [ $gmappingNumber -le 0 ];then
   echo "gmapping is not run"
else
   echo "gmapping is  running,need kill"
   killall rosmaster
fi

move_base_Name=move_base
move_baseNumber=`ps -ef |grep -w $move_base_Name|grep -v grep|wc -l`
if [ $move_baseNumber -le 0 ];then
   echo "need turn on move_base"
   bash /home/pc-01/food_delivery_robot/script/web/fallback_navigation/navigation_start

else
   echo "move_base is running"
fi
exit
