#!/bin/bash
 
source /opt/ros/kinetic/setup.bash
source /home/pc-01/food_delivery_robot/devel/setup.bash
if [ $#==1 ]
then
  roslaunch robot_navigation laser_teb.launch global_map:=$1
else
  roslaunch robot_navigation laser_teb.launch
fi
