#!/bin/bash
rosnode kill rplidarNode
killall main_cpp
killall robot_bringup
killall amcl
killall robot_pose_ekf
killall nodelet
killall map_server
killall move_base
killall python
killall python2
killall scan_to_scan_filter_chain
killall static_transform_publisher
killall tf2_web_republisher
killall ros_launch
killall rosmaster
