#!/bin/bash


if [ ! -e "/dev/robot" ]; then
  zenity --error --text="底层连接失败，请检查机器人是否连接至上位机，并确保上位机控制开关打开以及急停按钮未按下。"
  exit 0
fi

if [ ! -e "/dev/rplidar" ]; then
  zenity --error --text="单线激光雷达连接失败，请检查雷达是否连接至上位机。"
  exit 0
fi


source /home/pc-01/food_delivery_robot/devel/setup.bash
IP=`ifconfig wlan0 | grep "inet 地址:" | awk '{print $2}' | cut -c 8-`

if [ -z "$IP" ]; then
  IP="127.0.0.1"
fi

export ROS_HOSTNAME=pc01
export ROS_MASTER_URI=http://pc01:11311     #（当前终端有效）保存，退出
source /opt/ros/kinetic/setup.bash
source /home/pc-01/food_delivery_robot/devel/setup.bash

roslaunch robot_navigation build_map.launch

