#!/bin/bash
source /opt/ros/kinetic/setup.bash
source ~/food_delivery_robot/devel/setup.bash
roscd robot_navigation/map
if [ $#==1 ]
then
  rosrun map_server map_saver -f $1
else
  rosrun map_server map_saver
fi
exit
